/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CarteirasRouteImport } from './routes/carteiras'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasRoute = CarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteiras': typeof CarteirasRoute
  '/criadores': typeof CriadoresRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteiras': typeof CarteirasRoute
  '/criadores': typeof CriadoresRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteiras': typeof CarteirasRoute
  '/criadores': typeof CriadoresRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho'
    | '/carteiras'
    | '/criadores'
    | '/favoritos'
    | '/login'
    | '/mercado'
    | '/pagamento'
    | '/perfil'
    | '/nft/$nftId'
    | '/pedido/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho'
    | '/carteiras'
    | '/criadores'
    | '/favoritos'
    | '/login'
    | '/mercado'
    | '/pagamento'
    | '/perfil'
    | '/nft/$nftId'
    | '/pedido/$orderId'
  id:
    | '__root__'
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho'
    | '/carteiras'
    | '/criadores'
    | '/favoritos'
    | '/login'
    | '/mercado'
    | '/pagamento'
    | '/perfil'
    | '/nft/$nftId'
    | '/pedido/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendaRoute: typeof AprendaRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CarteirasRoute: typeof CarteirasRoute
  CriadoresRoute: typeof CriadoresRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  PagamentoRoute: typeof PagamentoRoute
  PerfilRoute: typeof PerfilRoute
  NftNftIdRoute: typeof NftNftIdRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras': {
      id: '/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof CarteirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendaRoute: AprendaRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CarteirasRoute: CarteirasRoute,
  CriadoresRoute: CriadoresRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  PagamentoRoute: PagamentoRoute,
  PerfilRoute: PerfilRoute,
  NftNftIdRoute: NftNftIdRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
